#line 6 "/home/dav480/tcl/nap/generic/include.m4"

#line 5 "/home/dav480/tcl/nap/generic/linsys.h,m4"
/* Do not edit this file (linsys.h). It was produced from source file linsys.h,m4 */

/*
 * linsys.h,m4 --
 *
 *	This routine 'linsys' came from
 *	http://www.fysik.dtu.dk/~stoltze/tools/linsys/linsys.htm
 *
 * $Id: linsys.h,m4,v 1.4 2002/05/14 00:32:03 dav480 Exp $
 */

#ifndef _LINSYS
#define _LINSYS

#include "nap.h"
#include "nap_check.h"

#line 36 "/home/dav480/tcl/nap/generic/linsys.h,m4"


#line 37

#line 37
EXTERN int
#line 37
linsys_F32(
#line 37
	NapClientData       *nap_cd,
#line 37
	int n,				/* # rows in a and b */
#line 37
	int m,				/* # columns in b */
#line 37
	Nap_f32 **a,		/* pointers to rows of main matrix (left hand side) */
#line 37
	Nap_f32 **b);	/* pointers to rows of right hand side */
#line 37

#line 37

#line 37
EXTERN int
#line 37
linsys_F64(
#line 37
	NapClientData       *nap_cd,
#line 37
	int n,				/* # rows in a and b */
#line 37
	int m,				/* # columns in b */
#line 37
	Nap_f64 **a,		/* pointers to rows of main matrix (left hand side) */
#line 37
	Nap_f64 **b);	/* pointers to rows of right hand side */
#line 37

#line 37


#endif /* _LINSYS */
