#line 6 "/home/dav480/tcl/nap/generic/include.m4"

#line 5 "/home/dav480/tcl/nap/generic/napChoice.c,m4"
/* Do not edit this file (napChoice.c) */
/* It was produced from source file napChoice.c,m4 */

/* 
 *	numeric array processor (nap)
 *
 *	Copyright 1997, CSIRO Australia
 *	Author: Harvey Davies, CSIRO Mathematical and Information Sciences
 */

#ifndef lint
static char *rcsid="@(#) $Id: napChoice.c,m4,v 1.37 2005/06/23 08:24:52 dav480 Exp $";
#endif /* not lint */

#include "nap.h"
#include "nap_check.h"

#line 69 "/home/dav480/tcl/nap/generic/napChoice.c,m4"



EXTERN char *
Nap_Choice(
    NapClientData	*nap_cd,
    char		*str1,			/* id of test nao */
    char		*str2)			/* id of boxed nao */
{
    Nap_NAO             *coordNaoPtr;           /* coordinate variable */
    Nap_dataType        dataType;
    char                *dimName;               /* dimension name */
    int			i;
    int			j;
    int			k;
    int			nels;
    Nap_NAO		*new;			/* result */
    int                 rank;
    size_t              *shape;
    int                 status;
    Nap_NAO		*nao2;			/* promoted "if true" nao arg */
    Nap_NAO		*nao3;			/* promoted "if false" nao arg */
    Nap_NAO		*naoPtr1;		/* test nao arg */
    Nap_NAO		*naoPtr2;		/* "if true" nao arg */
    Nap_NAO		*naoPtr3;		/* "if false" nao arg */
    Nap_NAO		*naoPtrBoxed;		/* boxed nao arg */
    int                 test;			/* temp. boolean */

    naoPtr1 = Nap_GetNumericNaoFromId(nap_cd, str1);
    CHECK2NULL(naoPtr1, "Nap_Choice: Undefined left-hand operand of '?'");
    naoPtrBoxed = Nap_GetNaoFromId(nap_cd, str2);
    CHECK2NULL(naoPtrBoxed, "Nap_Choice: Undefined right-hand operand of '?'");
    CHECK2NULL(naoPtrBoxed->dataType == NAP_BOXED,
	    "Nap_Choice: Right-hand operand of '?' is not boxed");
    Nap_IncrRefCount(nap_cd, naoPtrBoxed);
    naoPtr2 = Nap_GetNaoFromSlot(naoPtrBoxed->data.Boxed[0]);
    naoPtr3 = Nap_GetNaoFromSlot(naoPtrBoxed->data.Boxed[1]);
    CHECK2NULL(naoPtr2, "Nap_Choice: Undefined middle operand. x?NULL:z");
    CHECK2NULL(naoPtr3, "Nap_Choice: Undefined right-hand operand. x?y:NULL");
    Nap_IncrRefCount(nap_cd, naoPtr1);
    Nap_IncrRefCount(nap_cd, naoPtr2);
    Nap_IncrRefCount(nap_cd, naoPtr3);
    Nap_DecrRefCount(nap_cd, naoPtrBoxed);
    if (naoPtr1->rank == 0) {
	if (IsMissing(naoPtr1, 0)) {
	    new = Nap_NewNAO(nap_cd, NAP_I8, 0, NULL);
	    new->data.I8[0] = nap_cd->I8MissingValueNao->data.I8[0];
	} else {
	    switch (naoPtr1->dataType) {
		
#line 118

#line 118

#line 118

#line 118
	case NAP_U8:
#line 118
	    test = naoPtr1->data.U8[0];
#line 118
	    break;
#line 118

#line 118
	case NAP_U16:
#line 118
	    test = naoPtr1->data.U16[0];
#line 118
	    break;
#line 118

#line 118
	case NAP_U32:
#line 118
	    test = naoPtr1->data.U32[0];
#line 118
	    break;
#line 118

#line 118

#line 118

#line 118
	case NAP_I8:
#line 118
	    test = naoPtr1->data.I8[0];
#line 118
	    break;
#line 118

#line 118
	case NAP_I16:
#line 118
	    test = naoPtr1->data.I16[0];
#line 118
	    break;
#line 118

#line 118
	case NAP_I32:
#line 118
	    test = naoPtr1->data.I32[0];
#line 118
	    break;
#line 118

#line 118

#line 118

#line 118

#line 118
	case NAP_F32:
#line 118
	    test = naoPtr1->data.F32[0];
#line 118
	    break;
#line 118

#line 118
	case NAP_F64:
#line 118
	    test = naoPtr1->data.F64[0];
#line 118
	    break;
#line 118

#line 118

		default:            /* error */
		    return NULL;
	    }
	    new = test ? naoPtr2 : naoPtr3;
	}
    } else {
	rank = Max(naoPtr1->rank, Max(naoPtr2->rank, naoPtr3->rank));
	if (rank == naoPtr1->rank) {
	    shape = naoPtr1->shape;
	} else if (rank == naoPtr2->rank) {
	    shape = naoPtr2->shape;
	} else {
	    shape = naoPtr3->shape;
	}
	dataType = Nap_DataType2(naoPtr2->dataType, naoPtr3->dataType);
	new = Nap_NewNAO(nap_cd, dataType, rank, shape);
	CHECK2NULL(new, "Nap_Choice: Error calling Nap_NewNAO");
	nao2 = Nap_CastNAO(nap_cd, naoPtr2, dataType);
	nao3 = Nap_CastNAO(nap_cd, naoPtr3, dataType);
	Nap_IncrRefCount(nap_cd, nao2);
	Nap_IncrRefCount(nap_cd, nao3);
        for (i = 0; i < rank; i++) {
	    j = naoPtr1->rank - i - 1;
	    k = new->rank - i - 1;
	    CHECK3NULL(j < 0  ||  naoPtr1->shape[j] == new->shape[k], "Nap_Choice: "
		    "Left operand has different sized dimension %d from that of other operands",
		    j);
	    j = naoPtr2->rank - i - 1;
	    CHECK3NULL(j < 0  ||  naoPtr2->shape[j] == new->shape[k], "Nap_Choice: "
		    "Middle operand has different sized dimension %d from that of other operands",
		    j);
	    j = naoPtr3->rank - i - 1;
	    CHECK3NULL(j < 0  ||  naoPtr3->shape[j] == new->shape[k], "Nap_Choice: "
		    "Right operand has different sized dimension %d from that of other operands",
		    j);
	    coordNaoPtr = Nap_GetCoordVar(nap_cd, naoPtr1, i);
	    if (!coordNaoPtr) {
		coordNaoPtr = Nap_GetCoordVar(nap_cd, naoPtr2, i);
	    }
	    if (!coordNaoPtr) {
		coordNaoPtr = Nap_GetCoordVar(nap_cd, naoPtr3, i);
	    }
	    dimName = NULL;
	    if (i < naoPtr1->rank) {
		dimName = naoPtr1->dimName[i];
	    }
	    if (!dimName  &&  i < naoPtr2->rank) {
		dimName = naoPtr2->dimName[i];
	    }
	    if (!dimName  &&  i < naoPtr3->rank) {
		dimName = naoPtr3->dimName[i];
	    }
	    status = Nap_AttachCoordVar(nap_cd, new, coordNaoPtr, dimName, i);
	    CHECK1NULL(status == TCL_OK);
	}
	nels = new->nels;
	test =  nao2->isMissing == new->isMissing  &&
		nao3->isMissing == new->isMissing  &&
		nao2->missingValueSlot == new->missingValueSlot  &&
		nao3->missingValueSlot == new->missingValueSlot;
	switch (dataType) {
	    
#line 180

#line 180

#line 180

#line 180
	case NAP_U8:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else {
#line 180
			    new->data.U8[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U8[i % naoPtr2->nels] :
#line 180
				    nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U8[i] = nap_cd->U8MissingValueNao->data.U8[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.U8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao2->data.U8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U8MissingValueNao->data.U8[0] : nao3->data.U8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180
	case NAP_U16:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else {
#line 180
			    new->data.U16[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U16[i % naoPtr2->nels] :
#line 180
				    nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U16[i] = nap_cd->U16MissingValueNao->data.U16[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.U16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao2->data.U16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U16MissingValueNao->data.U16[0] : nao3->data.U16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180
	case NAP_U32:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else {
#line 180
			    new->data.U32[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.U32[i % naoPtr2->nels] :
#line 180
				    nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.U32[i] = nap_cd->U32MissingValueNao->data.U32[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.U32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao2->data.U32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.U32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->U32MissingValueNao->data.U32[0] : nao3->data.U32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180

#line 180

#line 180
	case NAP_I8:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else {
#line 180
			    new->data.I8[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I8[i % naoPtr2->nels] :
#line 180
				    nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I8[i] = nap_cd->I8MissingValueNao->data.I8[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.I8[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao2->data.I8[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I8[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I8MissingValueNao->data.I8[0] : nao3->data.I8[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180
	case NAP_I16:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else {
#line 180
			    new->data.I16[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I16[i % naoPtr2->nels] :
#line 180
				    nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I16[i] = nap_cd->I16MissingValueNao->data.I16[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.I16[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao2->data.I16[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I16[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I16MissingValueNao->data.I16[0] : nao3->data.I16[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180
	case NAP_I32:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else {
#line 180
			    new->data.I32[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.I32[i % naoPtr2->nels] :
#line 180
				    nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.I32[i] = nap_cd->I32MissingValueNao->data.I32[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.I32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao2->data.I32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.I32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->I32MissingValueNao->data.I32[0] : nao3->data.I32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180

#line 180

#line 180

#line 180
	case NAP_F32:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else {
#line 180
			    new->data.F32[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F32[i % naoPtr2->nels] :
#line 180
				    nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F32[i] = nap_cd->F32MissingValueNao->data.F32[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.F32[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao2->data.F32[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F32[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F32MissingValueNao->data.F32[0] : nao3->data.F32[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180
	case NAP_F64:
#line 180
	    switch (naoPtr1->dataType) {
#line 180
	    
#line 180

#line 180

#line 180

#line 180
	    case NAP_U8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.U8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.U8[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.U16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.U16[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_U32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.U32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.U32[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180
	    case NAP_I8:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.I8[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.I8[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I16:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.I16[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.I16[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_I32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.I32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.I32[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180

#line 180

#line 180
	    case NAP_F32:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.F32[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.F32[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180
	    case NAP_F64:
#line 180
		if (test) {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else {
#line 180
			    new->data.F64[i] = naoPtr1->data.F64[i % naoPtr1->nels] ?
#line 180
				    nao2->data.F64[i % naoPtr2->nels] :
#line 180
				    nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		} else {
#line 180
		    for (i = 0; i < nels; i++) {
#line 180
			if (IsMissing(naoPtr1, i)) {
#line 180
			    new->data.F64[i] = nap_cd->F64MissingValueNao->data.F64[0];
#line 180
			} else if (naoPtr1->data.F64[i % naoPtr1->nels]) {
#line 180
			    new->data.F64[i] = IsMissing(nao2, i % naoPtr2->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao2->data.F64[i % naoPtr2->nels];
#line 180
			} else {
#line 180
			    new->data.F64[i] = IsMissing(nao3, i % naoPtr3->nels) ?
#line 180
				    nap_cd->F64MissingValueNao->data.F64[0] : nao3->data.F64[i % naoPtr3->nels];
#line 180
			}
#line 180
		    }
#line 180
		}
#line 180
		break;
#line 180

#line 180

#line 180
	    default:                /* error */
#line 180
		return NULL;
#line 180
	    }
#line 180
	    break;
#line 180

#line 180

	    default:            /* error */
		return NULL;
	}
	Nap_DecrRefCount(nap_cd, nao2);
	Nap_DecrRefCount(nap_cd, nao3);
    }
    Nap_IncrRefCount(nap_cd, new);		/* In case new == naoPtr2 or naoPtr3 */
    Nap_DecrRefCount(nap_cd, naoPtr1);
    Nap_DecrRefCount(nap_cd, naoPtr2);
    Nap_DecrRefCount(nap_cd, naoPtr3);
    -- new->count;
    return new->id;
}
