set p moll
nap "lat = 90 .. -90"
nap "lon = -180 .. 180"
nap "m = is_land(lat, lon)"
nap "latmat = transpose(reshape(lat, {361 181}))"
nap "xy = cart_proj_fwd(lon, latmat, 'proj=$p')"
nap "x = open_box(xy 0)"
nap "y = open_box(xy 1)"
nap "xv = 401 ... min(min(x)) .. max(max(x))"
nap "yv = max(max(y)) .. min(min(y)) ...  xv(0) - xv(1)"
nap "ym = transpose(reshape(yv, nels(xv) // nels(yv)))"
nap "b = cart_proj_inv(xv, ym, 'proj=$p')"
nap "lons = open_box(b 0)"
nap "lats = open_box(b 1)"
nap "i = lat @ lats"
nap "j = lon @ lons"
nap "ij = transpose(i /// j, {1 2 0})"
plot_nao "m(ij)"
