/*
 * land_flag_i.c --
 *
 * Copyright (c) 2004, CSIRO Australia
 *
 * This file was originally generated by tcl procedure 'make_dll_i' on 2004-07-07 at 11:33.
 * It defines interface between tcl command 'nap_land_flag' & C function 'land_flag'.
 * land_flag was merged into nap in August 2004. Some mods were made in this process.
 */

#include <nap.h>
#include "land_flag.h"

#define NUM_ARGS 9

int
Land_flagInt(
    ClientData          clientData,
    Tcl_Interp          *interp,
    int                 objc,
    Tcl_Obj *CONST      objv[])
{
    NapClientData       *nap_cd = Nap_GetClientData(interp);
    Nap_NAO             *naoArgPtr;
    Nap_NAO             *naoPtr[NUM_ARGS];
    char                *arg;

    if (objc == NUM_ARGS + 1) {
        arg = Tcl_GetStringFromObj(objv[1], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[0] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_C8);
            Nap_IncrRefCount(nap_cd, naoPtr[0]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 1 (dir) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[2], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[1] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_I32);
            Nap_IncrRefCount(nap_cd, naoPtr[1]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 2 (y) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[3], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[2] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_I32);
            Nap_IncrRefCount(nap_cd, naoPtr[2]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 3 (x) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[4], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[3] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_F32);
            Nap_IncrRefCount(nap_cd, naoPtr[3]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 4 (latitude) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[5], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[4] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_F32);
            Nap_IncrRefCount(nap_cd, naoPtr[4]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 5 (longitude) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[6], NULL);
        naoPtr[5] = Nap_GetNaoFromId(nap_cd, arg);
        if (naoPtr[5]) {
            if (naoPtr[5]->dataType != NAP_I8) {
                Tcl_SetResult(interp,
                    "nap_land_flag: Argument 6 (result) is not I8\n", NULL);
                return TCL_ERROR;
            }
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 6 (result) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[7], NULL);
        naoPtr[6] = Nap_GetNaoFromId(nap_cd, arg);
        if (naoPtr[6]) {
            if (naoPtr[6]->dataType != NAP_I32) {
                Tcl_SetResult(interp,
                    "nap_land_flag: Argument 7 (err) is not I32\n", NULL);
                return TCL_ERROR;
            }
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 7 (err) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[8], NULL);
        naoPtr[7] = Nap_GetNaoFromId(nap_cd, arg);
        if (naoPtr[7]) {
            if (naoPtr[7]->dataType != NAP_C8) {
                Tcl_SetResult(interp,
                    "nap_land_flag: Argument 8 (msg) is not C8\n", NULL);
                return TCL_ERROR;
            }
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 8 (msg) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        arg = Tcl_GetStringFromObj(objv[9], NULL);
        naoArgPtr = Nap_GetNumericNaoFromId(nap_cd, arg);
        if (naoArgPtr) {
            naoPtr[8] = Nap_CastNAO(nap_cd, naoArgPtr, NAP_I32);
            Nap_IncrRefCount(nap_cd, naoPtr[8]);
            Nap_IncrRefCount(nap_cd, naoArgPtr);
            Nap_DecrRefCount(nap_cd, naoArgPtr);
        } else {
            Tcl_SetResult(interp,
                "nap_land_flag: Argument 9 (mxsz) is not NAO\n", NULL);
            return TCL_ERROR;
        }
        (void) land_flag(
                naoPtr[0]->data.C8,
                naoPtr[1]->data.I32,
                naoPtr[2]->data.I32,
                naoPtr[3]->data.F32,
                naoPtr[4]->data.F32,
                naoPtr[5]->data.I8,
                naoPtr[6]->data.I32,
                naoPtr[7]->data.C8,
                naoPtr[8]->data.I32);
        Nap_DecrRefCount(nap_cd, naoPtr[0]);
        Nap_DecrRefCount(nap_cd, naoPtr[1]);
        Nap_DecrRefCount(nap_cd, naoPtr[2]);
        Nap_DecrRefCount(nap_cd, naoPtr[3]);
        Nap_DecrRefCount(nap_cd, naoPtr[4]);
        Nap_DecrRefCount(nap_cd, naoPtr[8]);
    } else {
        Tcl_WrongNumArgs(interp, 1, objv, "dir y x latitude longitude result err msg mxsz");
        return TCL_ERROR;
    }
    Tcl_ResetResult(interp);
    return TCL_OK;
}

EXTERN int
Land_flag_Init(
    Tcl_Interp          *interp)
{
    Tcl_CreateObjCommand(interp, "nap_land_flag",  Land_flagInt, NULL, NULL);
    return TCL_OK;
}
